SHELL := /usr/bin/env -S bash
CC = gcc

CFLAGS = -Wall -Wextra -Wpedantic -fanalyzer -Wanalyzer-too-complex -Og -ggdb

CFLAGS +=
LDLIBS +=
LDFLAGS +=

.PHONY: clean

main: main.c

clean:
	rm -rvf main
